# Generated by Django 5.2.8 on 2025-11-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickmodel',
            old_name='latinName',
            new_name='latin_name',
        ),
    ]
