# Generated by Django 5.2.8 on 2025-11-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_latinname_tickmodel_latin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
