# Generated by Django 5.2.8 on 2025-11-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tickmodel_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickmodel',
            name='unique_title_in_artist',
        ),
        migrations.AddConstraint(
            model_name='tickmodel',
            constraint=models.UniqueConstraint(fields=('location', 'date'), name='unique_title_in_artist'),
        ),
    ]
