# Generated by Django 5.2.8 on 2025-11-22 21:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tickmodel_unique_title_in_artist_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tickmodel',
            name='unique_title_in_artist',
        ),
        migrations.AlterField(
            model_name='tickmodel',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(datetime.datetime(2025, 11, 22, 21, 19, 43, 394922))]),
        ),
        migrations.AddConstraint(
            model_name='tickmodel',
            constraint=models.UniqueConstraint(fields=('location', 'date'), name='unique_location_to_time'),
        ),
    ]
