# Generated by Django 5.2.8 on 2025-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tickmodel_unique_title_in_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
