# Generated by Django 5.2.8 on 2025-11-22 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tickmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickmodel',
            name='date',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator('2025-11-22T21:50:19')]),
        ),
    ]
